const baseStyles = {
    margin: '0px',
    padding: '0px',
    alignSelf: 'unset',
    display: 'block',
    width: '50%',
    maxWidth: 'unset',
    minWidth: 'unset',
    height: 'auto',
    maxHeight: 'unset',
    minHeight: 'unset',
    background: 'none',
    borderRadius: '16px',
    zIndex: 1200,
    position: 'relative',
  };